title: WinNvm
description: A Node Version Manager.
exclude:
 # from https://github.com/jekyll/jekyll/blob/master/lib/site_template/_config.yml:
   - .sass-cache/
   - .jekyll-cache/
   - gemfiles/
   - Gemfile
   - Gemfile.lock
   - node_modules/
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
 # specific to the theme website:
   - bin/
   - lib/
   - "*.gemspec"
   - "*.gem"
   - LICENSE.txt
   - package.json
   - package-lock.json
   - Rakefile
   - README.md
   - CODE_OF_CONDUCT.md
   - docker-compose.yml
   - Dockerfile
 # theme test code
   - fixtures/
   
theme: just-the-docs

url: https://winnvm.github.io

# Aux links for the upper right navigation
aux_links:
  "GitHub": "//github.com/winnvm/winnvm"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

heading_anchors: true
